DrinkingWebsite/DrinkingWebsite/Controllers/AboutAddictionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Text;

namespace DrinkingWebsite.Controllers
{
    public class AboutAddictionController : Controller
    {
        // GET: AboutAddiction
        /// <summary>
        /// Alcoholism page's controller
        /// </summary>
        /// <returns>Alcoholism view</returns>
        public ActionResult Index()
        {
            return View();
        }
    }
}

DrinkingWebsite/DrinkingWebsite/Controllers/AboutAlcoholController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DrinkingWebsite.Controllers
{
    public class AboutAlcoholController : Controller
    {
        // GET: AboutAlcohol
        public ActionResult Index()
        {
            return View();
        }
    }
}

DrinkingWebsite/DrinkingWebsite/Controllers/AboutPageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DrinkingWebsite.Controllers
{
    public class AboutPageController : Controller
    {
        // GET: AboutPage
        public ActionResult Index()
        {
            return View();
        }
    }
}

DrinkingWebsite/DrinkingWebsite/Controllers/BACController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DrinkingWebsite.Controllers
{
    public class BACController : Controller
    {
        // GET: BAC
        public ActionResult Index()
        {
            return View();
        }
    }
}

DrinkingWebsite/DrinkingWebsite/Controllers/BACalculateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DrinkingWebsite.Controllers
{
    public class BACalculateController : Controller
    {
        // GET: BACalculate
        public ActionResult Index()
        {
            return View();
        }
    }
}

DrinkingWebsite/DrinkingWebsite/Controllers/BACalculateOneController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DrinkingWebsite.Controllers
{
    public class BACalculateOneController : Controller
    {
        // GET: BACalculateOne
        public ActionResult Index()
        {
            return View();
        }
    }
}

DrinkingWebsite/DrinkingWebsite/Controllers/ContactUsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DrinkingWebsite.Controllers
{
    public class ContactUsController : Controller
    {
        // GET: ContactUs
        public ActionResult Index()
        {
            return View();
        }
    }
}

DrinkingWebsite/DrinkingWebsite/Controllers/DisclaimerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DrinkingWebsite.Controllers
{
    public class DisclaimerController : Controller
    {
        // GET: Disclaimer
        public ActionResult Index()
        {
            return View();
        }
    }
}

DrinkingWebsite/DrinkingWebsite/Controllers/ErrorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DrinkingWebsite.Controllers
{
    public class ErrorController : Controller
    {
        // GET: Error
        public ActionResult Index()
        {
            return View();
        }
    }
}

DrinkingWebsite/DrinkingWebsite/Controllers/GuideController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DrinkingWebsite.Controllers
{
    public class GuideController : Controller
    {
        // GET: Guide
        public ActionResult Index()
        {
            return View();
        }
    }
}

DrinkingWebsite/DrinkingWebsite/Controllers/PrivacyPolicyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DrinkingWebsite.Controllers
{
    public class PrivacyPolicyController : Controller
    {
        // GET: PrivacyPolicy
        public ActionResult Index()
        {
            return View();
        }
    }
}

DrinkingWebsite/DrinkingWebsite/Controllers/QuestionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DrinkingWebsite.Controllers
{
    public class QuestionController : Controller
    {
        // GET: Question
        public ActionResult Index()
        {
            return View();
        }
    }
}

DrinkingWebsite/DrinkingWebsite/Controllers/ResourcesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DrinkingWebsite.Controllers
{
    public class ResourcesController : Controller
    {
        // GET: Resources
        public ActionResult Index()
        {
            return View();
        }
    }
}

DrinkingWebsite/DrinkingWebsite/Controllers/SDCalculateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DrinkingWebsite.Controllers
{
    public class SDCalculateController : Controller
    {
        // GET: SDCalculate
        public ActionResult Index()
        {
            return View();
        }
    }
}

DrinkingWebsite/DrinkingWebsite/Controllers/SignInController.cs
using DrinkingWebsite.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DrinkingWebsite.Controllers
{
 
    public class SignInController : Controller
    {
        DataContext db = new DataContext();
        // GET: SignIn
        /// <summary>
        /// first page of our website
        /// use to isolate people unrelated to our project
        /// </summary>
        /// <returns>sign in view</returns>
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(string Password)
        {
            var data = db.loginInfos.SqlQuery("SELECT * FROM LoginInfo").ToList();
            if (data.Count() > 0)
            {
                if (data.Where(x => x.LoginID == 1 && x.Password == Password).Count() > 0)
                {
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ViewBag.msg = "Password is invalid.";
                }
            }
            return View();
        }
    }
}

DrinkingWebsite/DrinkingWebsite/Views/BACalculateOne/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="~/Content/blog.css" rel="stylesheet" />
<style>


    .blog-post {
        margin-bottom: 1rem;
    }

    .table-sm th {
        padding: 30px 40px;
    }

    .custom-control {
        display: inline-block;
        padding-left: 35px;
    }

    .btn-primary, .btn-primary:hover, .btn-primary:not(:disabled):not(.disabled):active {
        color: #fff;
        background-color: #ffcd3c;
        border-color: #ffcd3c;
    }

    .chen-nav-link:hover {
        color: #405d7e !important;
    }
</style>

<div class="container1" style="margin-top:40px;margin-bottom:40px;">
    <div class="row">
        <div class="col-md-12 blog-main">
            <h2 class="blog-post-title">
                Blood Alcohol Content
            </h2>
            <span style="margin-bottom: 2rem; display: block; width: 20%; height: 5px; background-color: #edab00;"></span>
            <div class="blog-post" style="word-wrap: break-word; word-break: normal;">
                <p class="lead">
                    Blood alcohol concentration(BAC) is the level of alcohol in your bloodstream and a good
                    indicator of intoxication. BAC is what police use in roadside breath tests to measure drunken
                    driving. If a person has a Blood alcohol concentration of 0.05% (point 0 five), then there is
                    0.05 g of alcohol in every 100 ml of blood(Australia’s upper legal limit for driving) .
                </p>
            </div>
        </div>
        <div class="col-md-12 blog-main">
            <h3 class="h3" style="margin-bottom:1rem;">
                Blood Alcohol Concentration Likely Behaviour Table
            </h3>
            <div class="table-responsive">
                <table class="table table-striped table-sm">
                    <thead style="background-color: #edab00;">
                        <tr>
                            <th>BAC*</th>
                            <th>Likely effects of Intoxication</th>
                        </tr>
                    </thead>
                    <tr>
                        <td>0.02–0.05 g / 100 ml</td>
                        <td>
                            <ul>
                                <li> Cheerful, relaxed, pleasant feelings of happiness and wellbeing</li>
                                <li> Decreasing inhibitions.</li>
                                <li> Judgment increasingly impaired.</li>
                                <li> Increased chance of accidents.</li>
                                <li> Impaired coordination.</li>
                                <li>
                                    BAC* 0.05 g / 100 ml = legal limit for driving (if fully licensed) in all
                                    Australian states and territories.
                                </li>
                            </ul>
                        </td>
                    </tr>
                    <tr>
                        <td>0.1–0.2 g / 100 ml</td>
                        <td>
                            <ul>
                                <li> Ataxia</li>
                                <li> Decreased ability to appropriately interpret and react to surroundings.</li>
                                <li> Poor judgment.</li>
                                <li> Loss of ‘self-control’.</li>
                                <li> Slurred speech.</li>
                                <li>
                                    Increasingly unpredictable behaviour.
                                </li>
                                <li>
                                    Labile mood.
                                </li>
                                <li>
                                    Potential for aggression.
                                </li>
                            </ul>
                        </td>
                    </tr>
                    <tr>
                        <td>0.2–0.3 g / 100 ml</td>
                        <td>
                            <ul>
                                <li> Marked ataxia and slurred speech.</li>
                                <li> Poor judgment.</li>
                                <li> Labile mood.</li>
                                <li> Nausea and Vomiting.</li>
                                <li> Double vision.</li>
                                <li>
                                    Memory loss
                                </li>
                            </ul>
                        </td>
                    </tr>
                    <tr>
                        <td>0.3–0.4 g / 100 ml</td>
                        <td>
                            <ul>
                                <li>
                                    Stage 1 anaesthesia (sleepiness, poor response to external stimuli,
                                    oblivion).
                                </li>
                                <li> Memory lapse.</li>
                                <li> Labile mood.</li>
                            </ul>
                        </td>
                    </tr>
                    <tr>
                        <td>> 0.40 g / 100 ml</td>
                        <td>
                            <ul>
                                <li>
                                    Respiratory failure.
                                </li>
                                <li> Coma.</li>
                                <li> Possible death.</li>
                            </ul>
                        </td>
                    </tr>
                </table>
            </div>

        </div>
        <div class="col-md-12 blog-main">
            <h3 class="h3" style="margin-bottom:1rem;">
                How to stay below 0.05?
            </h3>
            <div class="blog-post" style="word-wrap: break-word; word-break: normal;">
                <p>
                    ➢ For men of average size: Limit your consumption to 2 standard drinks in the first
                    hour, then 1 standard drink thereafter.
                </p>
                <p>➢ For women of average size: No more than one standard drink per hour.</p>
                <p style="font-weight:bold;">Note: This is only a guide. You might still register above 0.05% even if you follow this.</p>
            </div>
        </div>

        <div class="col-md-12 blog-main">
            <h3 class="h3" style="margin-bottom:1rem;">
                What factors affect Blood Alcohol Content?
            </h3>
            <div class="blog-post" style="word-wrap: break-word; word-break: normal;">
                <p>
                    There are several factors that can influence your blood alcohol level:
                </p>
                <p style="font-weight:bold;">1. Size</p>
                <p>Generally, the smaller you are, the less alcohol you can consume to stay in compliance.</p>
                <p style="font-weight:bold;">2. Empty stomach</p>
                <p>
                    Drinking occurs more quickly to someone who hasn't eaten recently rather than
                    someone who just ate. In the absence of food, alcohol can be absorbed more rapidly
                    into the body. However, eating won't prevent a person from getting drunk.
                </p>
                <p style="font-weight:bold;">3. Body fat</p>
                <p>
                    People who have more body fat will get drunk quicker.
                </p>
                <p style="font-weight:bold;">4. Gender</p>
                <p>
                    The body of a woman absorbs alcohol more rapidly than that of a man, as women
                    generally have a lower ratio of fat to lean tissue. As a result, a woman who drinks the
                    same amount of alcohol as a man will have a higher blood alcohol level faster than the
                    man.
                </p>
                <p style="font-weight:bold;">5. Inexperience</p>
                <p>
                    Inexperienced drinkers usually have a lower tolerance to alcohol, which means that
                    their BAC rises faster than that of experienced drinkers.
                </p>
            </div>
        </div>
    </div>
    <h3 class="h3">WANT TO CALCULATE BLOOD ALCOHOL CONTENT?</h3>
    <a class="btn btn-primary btn-lg" href="@Url.Action("Index", "BAC")" style="font-weight:700;">Blood alcohol concentration calculator</a>

</div>

DrinkingWebsite/DrinkingWebsite/Views/BingeDrinking/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="~/Content/blog.css" rel="stylesheet" />
@* sub navigation bat in BingeDrinking *@
<div class="container" style="margin-top:60px;">
    <div class="nav1-scroller py-1 mb-2" style="border-bottom: .1875rem solid #e0a200;">
        <nav1 class="nav1 d-flex justify-content-start" style="font-size:1.125rem;">
            <a class="p-2" style="color: #2A4E5F !important;" href="@Url.Action("Index","AboutAddiction")">Alcoholism</a><span class="p-2">|</span>

            <a class="p-2" style="color: #2A4E5F !important;" href="@Url.Action("Index","Reasons")">Reasons Why People Drink</a><span class="p-2">|</span>
            <a class="p-2" style="color: #2A4E5F !important;" href="@Url.Action("Index","Causes")">Causes and Risk Factors</a>
            <a class="p-2" style="color: #fff !important; background-color: #f0ad00;" href="@Url.Action("Index","BingeDrinking")">Binge Drinking</a>
            <a class="p-2" style="color: #2A4E5F !important;" href="@Url.Action("Index","StaySober")">Stay Sober</a><span class="p-2">|</span>
            <a class="p-2" style="color: #2A4E5F !important;" href="@Url.Action("Index","DataChart")">Drinking factsheet</a>
        </nav1>
    </div>
</div>
@* content *@
<main role="main" class="container">
    <div class="row">
        <div class="col-md-12 blog-main">
            <h2 class="blog-post-title">
                Binge Drinking
            </h2>
            <div class="blog-post" style="word-wrap: break-word; word-break: normal;">
                <p class="lead">Despite its seemingly harmless surface, binge drinking can have long-term health implications that far outweigh the short-term negative aspects. Women binge drink more than four drinks in one sitting, while men have more than six. Despite differences in amounts, binge drinking is still fuelled by the same reasons. </p>
            </div>
            <div class="blog-post" style="word-wrap: break-word; word-break: normal;">
                <h3 class="h3">People who binge drink</h3>
                <span style="margin-bottom: 1.5rem; display: block; width: 10%; height: 5px; background-color: #edab00;"></span>
                <ul>
                    <li class="lead">Drink occasionally but not every day.</li>
                    <li class="lead">They might be unaware of their own limitations.</li>
                    <li class="lead">The goal isn't necessarily to drink heavily.</li>
                    <li class="lead">Drink too much because of peer pressure.</li>
                    <li class="lead">Might feel awkward in social situations.</li>
                </ul>
            </div>

            <div class="blog-post" style="word-wrap: break-word; word-break: normal;">
                <h3 class="h3">Reasons for Binge Drinking</h3>
                <span style="margin-bottom: 3rem; display: block; width: 10%; height: 5px; background-color: #edab00;"></span>
            </div>
            <div class="blog-post" style="word-wrap: break-word; word-break: normal;">
                <h4 class="h4">You wanted to have a great time</h4>
                <p class="lead">The more drinks, the better the time? The answer is no. Despite drinking culture telling us to "drink until you drop", it is often the opposite that happens. You should consider all the fun you're going to have the next day when you're hungover and suffering the consequences. </p>
            </div>
            <div class="blog-post" style="word-wrap: break-word; word-break: normal;">
                <h4 class="h4">Feeling lonely, anxious and in need of a confidence boost</h4>
                <p class="lead">The feeling of social anxiety is the leading reason we set a rapid pace. You may be more relaxed and confident after drinking a couple of drinks. It's important to remember, however, that this is a temporary fix for a long-term problem, and you will find yourself back at square one once the alcohol wears off. You can seek assistance if you suspect that you drink to hide such issues. </p>
            </div>
            <div class="blog-post" style="word-wrap: break-word; word-break: normal;">
                <h4 class="h4">You wanted to be accepted</h4>
                <p class="lead">Often, we are tempted to follow the crowd rather than stand out from the crowd. It's worth pondering who you're putting time into if being accepted means a wicked hangover and a bunch of regrets.</p>
            </div>
            <div class="blog-post" style="word-wrap: break-word; word-break: normal;">
                <h4 class="h4">Peer pressure</h4>
                <p class="lead">Binge drinking can be discouraged by peer pressure. Your friends may try to put you under pressure to drink more than you should, so turn the tables and question them calmly. While they may simply be trying to make you have fun, you can make them see the impact of their behaviour by calling out their actions.</p>
            </div>
            <div class="blog-post" style="word-wrap: break-word; word-break: normal;">
                <h4 class="h4">You did not realize that you were binge drinking</h4>
                <p class="lead">Drinking too much alcohol can be a bit of a grey area. The night may start off slowly, but suddenly this fun activity can become risky quickly. Pace yourself by drinking one glass of water for every one you drink. Between every alcoholic drink, drink a glass of water, which will also slow down your consumption as well as sober you up.</p>
            </div>
        </div><!-- /.blog-main -->

    </div><!-- /.row -->

</main>

<script src='~/Scripts/jquery-3.4.1.min.js'></script>

DrinkingWebsite/DrinkingWebsite/Views/ContactUs/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="~/Content/blog.css" rel="stylesheet" />
<link href="~/Scripts/form-validation.css" rel="stylesheet" />

<style>
    .blog-post {
        margin-bottom: 2rem;
    }
</style>
<main role="main" class="container" style="margin-top:60px;margin-bottom:100px;">
    <div class="row">
        <div class="col-md-12 blog-main">
            <h2 class="blog-post-title">
                Contact
            </h2>
            <span style="margin-bottom: 2rem; display: block; width: 20%; height: 5px; background-color: #edab00;"></span>
            <div class="blog-post" style="word-wrap: break-word; word-break: normal;">
                <p class="lead">
                    Email us with any questions or inquiries. We would be happy to answer your questions.
                </p>
            </div>
        </div>
    </div>
    <form class="needs-validation" novalidate="">
        <div class="row">
            <div class="col-md-6 mb-3">
                <label for="firstName">First name</label>
                <input type="text" class="form-control" id="firstName" placeholder="" value="" required="">
                <div class="invalid-feedback">
                    Valid first name is required.
                </div>
            </div>
            <div class="col-md-6 mb-3">
                <label for="lastName">Last name</label>
                <input type="text" class="form-control" id="lastName" placeholder="" value="" required="">
                <div class="invalid-feedback">
                    Valid last name is required.
                </div>
            </div>
        </div>

       

        <div class="mb-3">
            <label for="email">Email <span class="text-muted">(Optional)</span></label>
            <input type="email" class="form-control" id="email" placeholder="you@example.com">
            <div class="invalid-feedback">
                Please enter a valid email address for shipping updates.
            </div>
        </div>

        <div class="mb-3">
            <label for="address">Message</label>
            <textarea type="text" class="form-control" id="address" placeholder="Message" required=""></textarea>
            <div class="invalid-feedback">
                Please enter your Message.
            </div>
        </div>

      
        <hr class="mb-4">
        <button class="btn btn-primary btn-lg btn-block" type="submit">Submit</button>
    </form>

</main>

<script src="~/Scripts/form-validation.js"></script>

DrinkingWebsite/DrinkingWebsite/Views/StaySober/Index.cshtml
@{ ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml"; }
<link href="~/Content/blog.css" rel="stylesheet" />

<div class="container" style="margin-top:60px;">
    <div class="nav1-scroller py-1 mb-2" style="border-bottom: .1875rem solid #e0a200;">
        <nav1 class="nav1 d-flex justify-content-start" style="font-size:1.125rem;">
            <a class="p-2" style="color: #2A4E5F !important;" href="@Url.Action("Index","AboutAddiction")">Alcoholism</a><span class="p-2">|</span>
            <a class="p-2" style="color: #2A4E5F !important;" href="@Url.Action("Index","Reasons")">Reasons Why People Drink</a><span class="p-2">|</span>
            <a class="p-2" style="color: #2A4E5F !important;" href="@Url.Action("Index","Causes")">Causes and Risk Factors</a><span class="p-2">|</span>
            <a class="p-2" style="color: #2A4E5F !important;" href="@Url.Action("Index","BingeDrinking")">Binge Drinking</a>
            <a class="p-2" style="color: #fff !important; background-color: #f0ad00;" href="@Url.Action("Index","StaySober")">Stay Sober</a>
            <a class="p-2" style="color: #2A4E5F !important;" href="@Url.Action("Index","DataChart")">Drinking factsheet</a>
        </nav1>
    </div>
</div>
<main role="main" class="container">
    <div class="row">
        <div class="col-md-12 blog-main">
            <h2 class="blog-post-title">
                How to drink but not get drunk
            </h2>
            <div class="blog-post" style="word-wrap: break-word; word-break: normal;">
                <h3 class="h3">Set your limits</h3>
                <span style="margin-bottom: 1rem; display: block; width: 10%; height: 5px; background-color: #edab00;"></span>
                <p class="lead">You should determine how many drinks you will drink beforehand and stick to that number. We shouldn't drink more than four alcoholic beverages daily, according to a group of clever scientists. Everyone has a different tolerance level, so choose one that fits your needs rather than your friends. Consider the price of drinks. Check your finances before you go out and decide what you can afford to spend. Additionally, you should know that not all alcohol contains the same amount of alcohol.To know more about Standard Drinks, <a href="@Url.Action("Index", "Guide")">click here</a>  </p>
                @*<div style="text-align:center;"><img src="~/images/new4.jpg" alt="Alternate Text" style="width:60%;display:inline-block;" /></div>*@
            </div>

            <div class="blog-post" style="word-wrap: break-word; word-break: normal;">
                <h3 class="h3">Avoid drinking too quickly</h3>
                <span style="margin-bottom: 1rem; display: block; width: 10%; height: 5px; background-color: #edab00;"></span>
                <p class="lead">You can avoid getting drunk by spacing out your drinks. Make sure to let some time pass between drinks (for example, an hour) before getting another.What's that tasty craft beer? Drink it more slowly so that you can savour it. It'll be much more enjoyable, and you'll get more bang for your buck. It can be helpful to drink water or soft drinks in between alcoholic drinks (and to drink the alcoholic drinks slowly). </p>
            </div>
            <div class="blog-post" style="word-wrap: break-word; word-break: normal;">
                <h3 class="h3">Try saying no</h3>
                <span style="margin-bottom: 1rem; display: block; width: 10%; height: 5px; background-color: #edab00;"></span>
                <p class="lead">
                    You may find peer pressure difficult to resist, but if you've had enough, turn down the offer of a drink when you've had enough. For now, you can alter the subject and let them know you're good. It's more important to keep track of your drinking than to keep up with others.
                    Although it's understandable that you might worry about ridicule if you don't drink, it's rare to see this. It doesn't matter if you drink slower than some of your friends (the good ones), they'll still hang out with you.
                </p>
            </div>

            <div class="blog-post" style="word-wrap: break-word; word-break: normal;">
                <h3 class="h3">Drinking shots and rounds is not advisable</h3>
                <span style="margin-bottom: 1rem; display: block; width: 10%; height: 5px; background-color: #edab00;"></span>
                <p class="lead">
                    Buying a drink for your friends is fine, but if you're with a group of seven, the session can quickly spiral out of control. If you do that, you could lose all your savings and break your bank.
                    Additionally, sipping drinks instead of shots allows you to space them out more easily. You can tell your friends not to shoot you, or you can just discreetly disappear when they're headed to the bar.
                </p>
            </div>
            <div class="blog-post" style="word-wrap: break-word; word-break: normal;">
                <h3 class="h3">A friend of water is a friend of food</h3>
                <span style="margin-bottom: 1rem; display: block; width: 10%; height: 5px; background-color: #edab00;"></span>
                <p class="lead">If you choose to drink alcohol, you should also have water or a non-alcoholic drink (it doesn't matter what the drink is). Having a meal is always a good idea if you are drinking. You will also (hopefully) get a delicious treat while slowing the effects of alcohol.</p>
            </div>
            <div class="blog-post" style="word-wrap: break-word; word-break: normal;">
                <h3 class="h3">Take time to focus on other things</h3>
                <span style="margin-bottom: 1rem; display: block; width: 10%; height: 5px; background-color: #edab00;"></span>
                <p class="lead">While drinking, engage in an activity such as playing pool. Drinking alcohol won't help you if you're already in a bad mood. Talk to a friend about how you're feeling or do something relaxing.</p>
            </div>
            <div class="blog-post" style="word-wrap: break-word; word-break: normal;">
                <h3 class="h3">Have a plan B</h3>
                <span style="margin-bottom: 1rem; display: block; width: 10%; height: 5px; background-color: #edab00;"></span>
                <p class="lead">
                    Make sure you have a mate to stay on top of your drinking and keep you from doing stupid stuff. In the event you drink too much, that friend will be able to help.
                    You should plan where you will sleep before you start drinking. You should have some money set aside for a taxi or Uber, just in case.
                </p>
            </div><!-- /.blog-main -->

        </div><!-- /.row -->

</main>
<script src='~/Scripts/jquery-3.4.1.min.js'></script>